version: '3.4'

services:

  db:
    image: docker.io/library/postgres:12
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432/tcp

  adminer:
    image: docker.io/library/adminer
    ports:
      - 8090:8080
