version: '3.4'

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432/tcp

  adminer:
    image: adminer
    ports:
      - 8090:8080
