services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://test:test@db:5432/test
      BASE_URL: http://localhost:3000
      DEBUG:
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
