version: '3.4'

services:

  app:
    image: docker.io/stormworks/feedropolis
    ports:
      - 3000:3000
    privileged: true
    environment:
      - DATABASE_URL=postgres://test:test@db:5432/test
      - BASE_URL=http://localhost:3000
      - DEBUG=

  db:
    image: docker.io/library/postgres:12
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
